// Regression tests: compare CUDA transformer forward pass against PyTorch reference
//
// Reference data generated by: python3 scripts/gen_transformer_reference.py
// using weights/transformer4/candidate_1.pth
//
// These tests catch:
//   - Weight transpose bugs (QKV, FFN)
//   - Shared memory aliasing (QK^T, attn×V)
//   - TC staging corruption
//   - Value head computation errors
//   - Board encoding mismatches

#include "../transformer_weights.cuh"
#include "../transformer_forward.cuh"
#include "../transformer_ops.cuh"
#include "../movegen.cuh"
#include "test_helpers.cuh"
#include <cstdio>
#include <cstring>
#include <cmath>

// ============================================================
// Helpers
// ============================================================

static float* load_ref(const char* path, int n_floats) {
    FILE* f = fopen(path, "rb");
    if (!f) return nullptr;
    float* buf = (float*)malloc(n_floats * sizeof(float));
    size_t got = fread(buf, sizeof(float), n_floats, f);
    fclose(f);
    if ((int)got != n_floats) { free(buf); return nullptr; }
    return buf;
}

static float max_abs_diff(const float* a, const float* b, int n) {
    float mx = 0.0f;
    for (int i = 0; i < n; i++) {
        float d = fabsf(a[i] - b[i]);
        if (d > mx) mx = d;
    }
    return mx;
}

static float mean_abs_diff(const float* a, const float* b, int n) {
    double sum = 0.0;
    for (int i = 0; i < n; i++) sum += fabsf(a[i] - b[i]);
    return (float)(sum / n);
}

static bool has_nan(const float* buf, int n) {
    for (int i = 0; i < n; i++) if (isnan(buf[i])) return true;
    return false;
}

// ============================================================
// Kernel: run board encoding only
// ============================================================

__global__ void kernel_encode_board(
    const BoardState* bs, float* tokens_out
) {
    extern __shared__ float smem[];
    float* tokens = smem;
    tf_board_to_tokens(bs, tokens);
    int tid = threadIdx.x;
    for (int i = tid; i < TF_NUM_TOKENS * NN_INPUT_CHANNELS; i += blockDim.x)
        tokens_out[i] = tokens[i];
}

// ============================================================
// Kernel: run full forward pass, output policy + value + k
// ============================================================

__global__ void kernel_full_forward(
    const BoardState* bs, float q_result,
    const TransformerWeights* weights,
    float* policy_out, float* value_out, float* k_out
) {
    extern __shared__ float smem[];
    float v, k;
    transformer_forward(bs, q_result, weights, nullptr, smem, policy_out, &v, &k);
    if (threadIdx.x == 0) { *value_out = v; *k_out = k; }
}

// ============================================================
// Kernel: run stages (input proj, pos emb, blocks) and dump
// ============================================================

__global__ void kernel_stages(
    const BoardState* bs,
    const TransformerWeights* weights,
    float* out_after_proj,   // [64, 128]
    float* out_after_posemb, // [64, 128]
    float* out_after_block0, // [64, 128]
    float* out_after_block5  // [64, 128]
) {
    extern __shared__ float smem[];
    int tid = threadIdx.x;
    const int T = TF_NUM_TOKENS, D = NN_HIDDEN_DIM;

    float* buf_x     = smem + TF_BUF_X_OFFSET;
    float* buf_out   = smem + TF_BUF_OUT_OFFSET;
    float* workspace = smem + TF_WORKSPACE_OFFSET;
    float* reduce    = smem + TF_REDUCE_OFFSET;

    // Board encoding
    float* tokens = workspace;
    tf_board_to_tokens(bs, tokens);

    // Input projection (scalar)
    for (int i = tid; i < T * D; i += blockDim.x) {
        int tok = i / D; int d = i % D;
        float sum = 0.0f;
        for (int c = 0; c < NN_INPUT_CHANNELS; c++)
            sum += tokens[tok * NN_INPUT_CHANNELS + c] * weights->input_proj_weight[d * NN_INPUT_CHANNELS + c];
        buf_out[i] = sum + weights->input_proj_bias[d];
    }
    __syncthreads();

    // Dump after proj
    for (int i = tid; i < T * D; i += blockDim.x) out_after_proj[i] = buf_out[i];

    // Add pos embedding
    for (int i = tid; i < T * D; i += blockDim.x)
        buf_x[i] = buf_out[i] + weights->pos_embedding[i];
    __syncthreads();

    // Dump after posemb
    for (int i = tid; i < T * D; i += blockDim.x) out_after_posemb[i] = buf_x[i];

    // Transformer blocks (replicating the forward pass logic)
    for (int blk = 0; blk < TF_NUM_LAYERS; blk++) {
        const TransformerBlock& block = weights->blocks[blk];

        // Attention
        tf_layer_norm(buf_x, buf_out, block.ln1.weight, block.ln1.bias, T, D, reduce);

        float res[32];
        for (int k = 0; k < 32; k++) res[k] = buf_x[tid + k * 256];
        for (int i = tid; i < T * D; i += blockDim.x) buf_x[i] = 0.0f;
        __syncthreads();

        float* ws_q    = workspace;
        float* ws_k    = workspace + T * TF_HEAD_DIM;
        float* ws_attn = workspace;
        float* ws_v    = workspace + T * T;

        for (int h = 0; h < TF_NUM_HEADS; h++) {
            int qkv_offset = h * TF_HEAD_DIM;

            // Q
            for (int i = tid; i < T * TF_HEAD_DIM; i += blockDim.x) {
                int tok = i / TF_HEAD_DIM; int d = i % TF_HEAD_DIM;
                float sum = 0.0f;
                for (int k = 0; k < D; k++)
                    sum += buf_out[tok * D + k] * block.qkv_weight[(qkv_offset + d) * D + k];
                ws_q[i] = sum + block.qkv_bias[qkv_offset + d];
            }
            __syncthreads();

            // K
            int k_offset = D + qkv_offset;
            for (int i = tid; i < T * TF_HEAD_DIM; i += blockDim.x) {
                int tok = i / TF_HEAD_DIM; int d = i % TF_HEAD_DIM;
                float sum = 0.0f;
                for (int k = 0; k < D; k++)
                    sum += buf_out[tok * D + k] * block.qkv_weight[(k_offset + d) * D + k];
                ws_k[i] = sum + block.qkv_bias[k_offset + d];
            }
            __syncthreads();

            // QK^T with local_results pattern
            float scale = rsqrtf((float)TF_HEAD_DIM);
            {
                float local_attn[16];
                int n_attn = (T * T + blockDim.x - 1) / blockDim.x;
                for (int e = 0; e < n_attn; e++) {
                    int i = tid + e * blockDim.x;
                    if (i >= T * T) break;
                    int row = i / T; int col = i % T;
                    float sum = 0.0f;
                    for (int d = 0; d < TF_HEAD_DIM; d++)
                        sum += ws_q[row * TF_HEAD_DIM + d] * ws_k[col * TF_HEAD_DIM + d];
                    local_attn[e] = sum * scale;
                }
                __syncthreads();
                for (int e = 0; e < n_attn; e++) {
                    int i = tid + e * blockDim.x;
                    if (i >= T * T) break;
                    ws_attn[i] = local_attn[e];
                }
                __syncthreads();
            }

            tf_softmax_rows(ws_attn, T, T, reduce);

            // V
            int v_offset = 2 * D + qkv_offset;
            for (int i = tid; i < T * TF_HEAD_DIM; i += blockDim.x) {
                int tok = i / TF_HEAD_DIM; int d = i % TF_HEAD_DIM;
                float sum = 0.0f;
                for (int k = 0; k < D; k++)
                    sum += buf_out[tok * D + k] * block.qkv_weight[(v_offset + d) * D + k];
                ws_v[i] = sum + block.qkv_bias[v_offset + d];
            }
            __syncthreads();

            // attn×V with local_results
            {
                float local_results[8];
                int n_elems = (T * TF_HEAD_DIM + blockDim.x - 1) / blockDim.x;
                for (int e = 0; e < n_elems; e++) {
                    int i = tid + e * blockDim.x;
                    if (i >= T * TF_HEAD_DIM) break;
                    int tok = i / TF_HEAD_DIM; int d = i % TF_HEAD_DIM;
                    float sum = 0.0f;
                    for (int k = 0; k < T; k++)
                        sum += ws_attn[tok * T + k] * ws_v[k * TF_HEAD_DIM + d];
                    local_results[e] = sum;
                }
                __syncthreads();
                for (int e = 0; e < n_elems; e++) {
                    int i = tid + e * blockDim.x;
                    if (i >= T * TF_HEAD_DIM) break;
                    ws_q[i] = local_results[e];
                }
                __syncthreads();
            }

            // Output projection
            for (int i = tid; i < T * D; i += blockDim.x) {
                int tok = i / D; int d = i % D;
                float sum = 0.0f;
                for (int j = 0; j < TF_HEAD_DIM; j++)
                    sum += ws_q[tok * TF_HEAD_DIM + j] * block.out_proj_weight[d * D + h * TF_HEAD_DIM + j];
                buf_x[i] += sum;
            }
            __syncthreads();
        }

        tf_add_bias(buf_x, block.out_proj_bias, T, D);
        for (int k = 0; k < 32; k++) buf_x[tid + k * 256] += res[k];
        __syncthreads();

        // FFN
        for (int k = 0; k < 32; k++) res[k] = buf_x[tid + k * 256];
        tf_layer_norm(buf_x, buf_out, block.ln2.weight, block.ln2.bias, T, D, reduce);
        for (int i = tid; i < T * D; i += blockDim.x) buf_x[i] = 0.0f;
        __syncthreads();

        float* ws_tile = workspace;
        for (int tile = 0; tile < TF_FFN_DIM / TF_FFN_TILE; tile++) {
            int tile_start = tile * TF_FFN_TILE;
            for (int i = tid; i < T * TF_FFN_TILE; i += blockDim.x) {
                int tok = i / TF_FFN_TILE; int d = i % TF_FFN_TILE;
                float sum = 0.0f;
                for (int k = 0; k < D; k++)
                    sum += buf_out[tok * D + k] * block.ffn1_weight[(tile_start + d) * D + k];
                float val = sum + block.ffn1_bias[tile_start + d];
                ws_tile[i] = val > 0.0f ? val : 0.0f;
            }
            __syncthreads();
            for (int i = tid; i < T * D; i += blockDim.x) {
                int tok = i / D; int d = i % D;
                float sum = 0.0f;
                for (int j = 0; j < TF_FFN_TILE; j++)
                    sum += ws_tile[tok * TF_FFN_TILE + j] * block.ffn2_weight[d * TF_FFN_DIM + tile_start + j];
                buf_x[i] += sum;
            }
            __syncthreads();
        }

        tf_add_bias(buf_x, block.ffn2_bias, T, D);
        for (int k = 0; k < 32; k++) buf_x[tid + k * 256] += res[k];
        __syncthreads();

        // Dump after complete block (attention + FFN + residuals)
        if (blk == 0)
            for (int i = tid; i < T * D; i += blockDim.x) out_after_block0[i] = buf_x[i];
        if (blk == 5)
            for (int i = tid; i < T * D; i += blockDim.x) out_after_block5[i] = buf_x[i];
    }
}

// ============================================================
// Tests
// ============================================================

void test_board_encoding_matches_reference(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_tokens.bin", 64 * 17);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float* d_tokens; cudaMalloc(&d_tokens, 64 * 17 * sizeof(float));
    kernel_encode_board<<<1, 256, 64 * 17 * sizeof(float)>>>(d_bs, d_tokens);
    cudaDeviceSynchronize();

    float h_tokens[64 * 17];
    cudaMemcpy(h_tokens, d_tokens, sizeof(h_tokens), cudaMemcpyDeviceToHost);

    float md = max_abs_diff(h_tokens, ref, 64 * 17);
    printf("[max_diff=%.6f] ", md);
    ASSERT_TRUE(md < 1e-6f);

    cudaFree(d_bs); cudaFree(d_tokens); free(ref);
}

void test_input_proj_matches_pytorch(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_after_proj.bin", 64 * 128);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_proj, *d_posemb, *d_blk0, *d_blk5;
    cudaMalloc(&d_proj, 64*128*4); cudaMalloc(&d_posemb, 64*128*4);
    cudaMalloc(&d_blk0, 64*128*4); cudaMalloc(&d_blk5, 64*128*4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_stages, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_stages<<<1, 256, smem>>>(d_bs, d_w, d_proj, d_posemb, d_blk0, d_blk5);
    cudaDeviceSynchronize();

    float h_proj[64 * 128];
    cudaMemcpy(h_proj, d_proj, sizeof(h_proj), cudaMemcpyDeviceToHost);

    float md = max_abs_diff(h_proj, ref, 64 * 128);
    printf("[max_diff=%.6f] ", md);
    ASSERT_TRUE(md < 1e-5f);

    cudaFree(d_bs); cudaFree(d_proj); cudaFree(d_posemb);
    cudaFree(d_blk0); cudaFree(d_blk5);
    free_transformer_weights(d_w); free(ref);
}

void test_posemb_matches_pytorch(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_after_posemb.bin", 64 * 128);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_proj, *d_posemb, *d_blk0, *d_blk5;
    cudaMalloc(&d_proj, 64*128*4); cudaMalloc(&d_posemb, 64*128*4);
    cudaMalloc(&d_blk0, 64*128*4); cudaMalloc(&d_blk5, 64*128*4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_stages, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_stages<<<1, 256, smem>>>(d_bs, d_w, d_proj, d_posemb, d_blk0, d_blk5);
    cudaDeviceSynchronize();

    float h_posemb[64 * 128];
    cudaMemcpy(h_posemb, d_posemb, sizeof(h_posemb), cudaMemcpyDeviceToHost);

    float md = max_abs_diff(h_posemb, ref, 64 * 128);
    printf("[max_diff=%.6f] ", md);
    ASSERT_TRUE(md < 1e-5f);

    cudaFree(d_bs); cudaFree(d_proj); cudaFree(d_posemb);
    cudaFree(d_blk0); cudaFree(d_blk5);
    free_transformer_weights(d_w); free(ref);
}

void test_block0_matches_pytorch(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_after_block0.bin", 64 * 128);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_proj, *d_posemb, *d_blk0, *d_blk5;
    cudaMalloc(&d_proj, 64*128*4); cudaMalloc(&d_posemb, 64*128*4);
    cudaMalloc(&d_blk0, 64*128*4); cudaMalloc(&d_blk5, 64*128*4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_stages, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_stages<<<1, 256, smem>>>(d_bs, d_w, d_proj, d_posemb, d_blk0, d_blk5);
    cudaDeviceSynchronize();

    float h_blk0[64 * 128];
    cudaMemcpy(h_blk0, d_blk0, sizeof(h_blk0), cudaMemcpyDeviceToHost);

    ASSERT_TRUE(!has_nan(h_blk0, 64 * 128));
    float md = max_abs_diff(h_blk0, ref, 64 * 128);
    printf("[max_diff=%.6f] ", md);
    ASSERT_TRUE(md < 1e-4f);  // 6 blocks of FP32 accumulation

    cudaFree(d_bs); cudaFree(d_proj); cudaFree(d_posemb);
    cudaFree(d_blk0); cudaFree(d_blk5);
    free_transformer_weights(d_w); free(ref);
}

void test_block5_matches_pytorch(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_after_block5.bin", 64 * 128);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_proj, *d_posemb, *d_blk0, *d_blk5;
    cudaMalloc(&d_proj, 64*128*4); cudaMalloc(&d_posemb, 64*128*4);
    cudaMalloc(&d_blk0, 64*128*4); cudaMalloc(&d_blk5, 64*128*4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_stages, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_stages<<<1, 256, smem>>>(d_bs, d_w, d_proj, d_posemb, d_blk0, d_blk5);
    cudaDeviceSynchronize();

    float h_blk5[64 * 128];
    cudaMemcpy(h_blk5, d_blk5, sizeof(h_blk5), cudaMemcpyDeviceToHost);

    ASSERT_TRUE(!has_nan(h_blk5, 64 * 128));
    float md = max_abs_diff(h_blk5, ref, 64 * 128);
    printf("[max_diff=%.6f] ", md);
    ASSERT_TRUE(md < 1e-3f);  // error accumulates through 6 blocks

    cudaFree(d_bs); cudaFree(d_proj); cudaFree(d_posemb);
    cudaFree(d_blk0); cudaFree(d_blk5);
    free_transformer_weights(d_w); free(ref);
}

void test_policy_matches_pytorch(bool& test_failed) {
    float* ref = load_ref("cuda/test/reference_data/startpos_policy.bin", 4672);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_policy, *d_val, *d_k;
    cudaMalloc(&d_policy, 4672 * 4); cudaMalloc(&d_val, 4); cudaMalloc(&d_k, 4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_full_forward, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_full_forward<<<1, 256, smem>>>(d_bs, 0.0f, d_w, d_policy, d_val, d_k);
    cudaDeviceSynchronize();

    float h_policy[4672];
    cudaMemcpy(h_policy, d_policy, sizeof(h_policy), cudaMemcpyDeviceToHost);

    ASSERT_TRUE(!has_nan(h_policy, 4672));
    float md = max_abs_diff(h_policy, ref, 4672);
    float mn = mean_abs_diff(h_policy, ref, 4672);
    printf("[max_diff=%.6f mean=%.6f] ", md, mn);
    ASSERT_TRUE(md < 1e-3f);

    // Check top move matches
    int cuda_top = 0, ref_top = 0;
    for (int i = 1; i < 4672; i++) {
        if (h_policy[i] > h_policy[cuda_top]) cuda_top = i;
        if (ref[i] > ref[ref_top]) ref_top = i;
    }
    printf("[top: cuda=%d ref=%d] ", cuda_top, ref_top);
    ASSERT_EQ(cuda_top, ref_top);

    cudaFree(d_bs); cudaFree(d_policy); cudaFree(d_val); cudaFree(d_k);
    free_transformer_weights(d_w); free(ref);
}

void test_value_matches_pytorch(bool& test_failed) {
    // Reference: [v_logit_q0, value_q0, k, v_logit_q3, value_q3]
    float* ref = load_ref("cuda/test/reference_data/startpos_value.bin", 5);
    if (!ref) { printf("[no ref data] "); ASSERT_TRUE(true); return; }

    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); free(ref); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_policy, *d_val, *d_k;
    cudaMalloc(&d_policy, 4672 * 4); cudaMalloc(&d_val, 4); cudaMalloc(&d_k, 4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_full_forward, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);

    float ref_value_q0 = ref[1], ref_k = ref[2], ref_value_q3 = ref[4];

    // q=0
    kernel_full_forward<<<1, 256, smem>>>(d_bs, 0.0f, d_w, d_policy, d_val, d_k);
    cudaDeviceSynchronize();
    float h_val, h_k;
    cudaMemcpy(&h_val, d_val, 4, cudaMemcpyDeviceToHost);
    cudaMemcpy(&h_k, d_k, 4, cudaMemcpyDeviceToHost);

    printf("[q=0: val=%.6f ref=%.6f] ", h_val, ref_value_q0);
    ASSERT_NEAR(h_val, ref_value_q0, 1e-4f);
    ASSERT_NEAR(h_k, ref_k, 1e-4f);

    // q=3
    kernel_full_forward<<<1, 256, smem>>>(d_bs, 3.0f, d_w, d_policy, d_val, d_k);
    cudaDeviceSynchronize();
    cudaMemcpy(&h_val, d_val, 4, cudaMemcpyDeviceToHost);

    printf("[q=3: val=%.6f ref=%.6f] ", h_val, ref_value_q3);
    ASSERT_NEAR(h_val, ref_value_q3, 1e-4f);

    cudaFree(d_bs); cudaFree(d_policy); cudaFree(d_val); cudaFree(d_k);
    free_transformer_weights(d_w); free(ref);
}

void test_no_nan_in_forward_pass(bool& test_failed) {
    TransformerWeights* d_w = load_transformer_weights("weights/transformer4/candidate_1.bin");
    if (!d_w) { printf("[no weights] "); ASSERT_TRUE(true); return; }

    BoardState bs = make_starting_position();
    BoardState* d_bs; cudaMalloc(&d_bs, sizeof(BoardState));
    cudaMemcpy(d_bs, &bs, sizeof(BoardState), cudaMemcpyHostToDevice);

    float *d_policy, *d_val, *d_k;
    cudaMalloc(&d_policy, 4672 * 4); cudaMalloc(&d_val, 4); cudaMalloc(&d_k, 4);

    int smem = TF_SMEM_BYTES;
    cudaFuncSetAttribute(kernel_full_forward, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    kernel_full_forward<<<1, 256, smem>>>(d_bs, 0.0f, d_w, d_policy, d_val, d_k);
    cudaDeviceSynchronize();

    float h_policy[4672], h_val;
    cudaMemcpy(h_policy, d_policy, sizeof(h_policy), cudaMemcpyDeviceToHost);
    cudaMemcpy(&h_val, d_val, 4, cudaMemcpyDeviceToHost);

    ASSERT_TRUE(!has_nan(h_policy, 4672));
    ASSERT_TRUE(!isnan(h_val));

    cudaFree(d_bs); cudaFree(d_policy); cudaFree(d_val); cudaFree(d_k);
    free_transformer_weights(d_w);
}

// ============================================================
// Main
// ============================================================

int main() {
    printf("=== Transformer vs PyTorch Regression Tests ===\n");
    init_movegen_tables();
    cudaDeviceSetLimit(cudaLimitStackSize, 32768);

    int total = 0, passes = 0, failures = 0;

    RUN_TEST(test_board_encoding_matches_reference);
    RUN_TEST(test_input_proj_matches_pytorch);
    RUN_TEST(test_posemb_matches_pytorch);
    RUN_TEST(test_block0_matches_pytorch);
    RUN_TEST(test_block5_matches_pytorch);
    RUN_TEST(test_policy_matches_pytorch);
    RUN_TEST(test_value_matches_pytorch);
    RUN_TEST(test_no_nan_in_forward_pass);

    printf("\n%d/%d tests passed", passes, total);
    if (failures > 0) printf(", %d FAILED", failures);
    printf("\n");
    return failures > 0 ? 1 : 0;
}
